platform :ios, ‘9.0’
use_frameworks!

target 'chance_btc_wallet' do
 
    # 导航栏弹出下拉选择菜单
    pod 'LMDropdownView'
    # Alamofire 网络库
    pod 'Alamofire', '~> 4.0'
    # swift编写的各种加密算法，如：MD5，SHA1
    pod 'CryptoSwift'
    # 键盘控制
    pod 'IQKeyboardManagerSwift', '4.0.6'
    # swift解析json库
    pod 'SwiftyJSON'
    # 二维码扫描解码及生成二维码
    #pod 'SwiftQRCode'
    # 苹果底层保存密码keychain工具，https://github.com/marketplacer/keychain-swift
    pod 'KeychainSwift', '~> 7.0'
    # 日志输出管理
    pod 'Log', '~> 1.0'
    # Swfit项目语言本地化支持框架： https://github.com/marmelroy/Localize-Swift
    pod 'Localize-Swift', '~> 1.5'
    # TabbarController组件：https://github.com/eggswift/ESTabBarController
    pod 'ESTabBarController-swift'
    # 分页滑动卡片组件：https://github.com/zhiquan911/CHPageCardView
    pod 'CHPageCardView', :git => 'https://github.com/zhiquan911/CHPageCardView.git', :branch => 'master'
    # 刷新数据组件：https://github.com/eggswift/pull-to-refresh
    pod 'ESPullToRefresh'
    
end


